spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vredu?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    
  freemarker:
    template-loader-path:
    - classpath:/templates
    content-type: text/html; charset=utf-8
    cache: false
    suffix: .ftl
    request-context-attribute: request
    enabled: true
    check-template-location: true
    
  